#!/usr/bin/env bash
# Installs nginx and configures it to return "Holberton School" at /
apt-get update -y
apt-get install -y nginx
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sed -i 's/listen 80 default_server;/listen 80 default_server;/' /etc/nginx/sites-available/default
service nginx restart

