#!/usr/bin/env bash
# Configures nginx to redirect /redirect_me to a YouTube video
apt-get update -y
apt-get install -y nginx
sed -i '/server_name _;/a location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default
service nginx restart

